### ISSUE TITLE
WES endpoints for Consonance

### ISSUE THREAD

**Issue by achave11** [BD2KGenomics/consonance#14]
### **Implement Workflow Execution Service API, for Consonance.**

**Purpose:**  By using the GA4GH-WES schema, we have a systematic method for carrying on existing functionalities, as well as introducing new features like delete, provided by the schemas requirements.

#### **Existing Milestone 1.5**
- [x] #12 Implement `getServiceInfo` endpoint.
- [x] #13 Test `getServiceInfo` endpoint, (build a test that exhibits functionality).
- [x] #16 Implement/integrate parallel client for ga4gh, namely `swagger-ga4gh-client`.
- [x] #12 Have callable objects to implement functionalities across project.
- [x] #11  Find preliminaries for implementing a functional call across the service.
- [x] #10 By using IDE, one can properly observe behavior (contained) of API endpoint implementation.     

#### **Milestone 2 `Tentative`**
- [x] Implement `getWorkflowStatus` **GET** _wes/v1/workflows/{workflows_id}/status_
- [ ] Test `getWorkflowStatus` endpoint, (build a test that exhibits functionality).
- [x] Implement `listWorkflows` **GET** _wes/v1/workflows_
- [ ] Test `listWorkflows` endpoint, (build a test that exhibits functionality).
- [x] Implement `getWorkflowLog` **GET** _wes/v1/workflows/{workflow_id}_
- [ ] Test `getWorkflowLog` endpoint, (build a test that exhibits functionality).
- [x] Implement `runWorkflow` **POST** _wes/v1/workflows_
- [ ] Test `runWorkflow` endpoint, (build a test that exhibits functionality).

#### **Milestone 3 `Tentative`**
- [ ] Implement delete functionality in system
- [ ] Implement `cancelJob` **DELETE** _/wes/v1/workflows/{workflow_id}_
- [ ] Test `cancelJob` endpoint, (build a test that exhibits functionality).
- [ ] Database update, tables, schemas, discussion with Brian.
- [ ] Implement database updates across system.
- [ ] Debug the pom, build the whole infrastructure without errors.

**NOTE:** This is tentative and desire progress, minor changes might be included to adjust actual progress.

**Comment by achave11** [comment]
Implementations in Milestone 2, have been tested on the AWS environment. 

No full end to end test available yet.
