### ISSUE TITLE
consonance sub-module for DCC-ops

### ISSUE THREAD

**Issue by achave11** [BD2KGenomics/consonance#21]
- [x] BUG problem with installing java inside docker containers.

- [x] Test end to end WES, run workflow and obtain results. 

- [x] Cherry pick Brian's consonance, and my consonance. 

- [ ] Release of consonance so that it can be pulled a submodule from dcc-ops.

- [ ] (help?) release dcc-ops so that it contains a submodule of consonance instead of a copy.

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/CON-11)
┆Project Name: Consonance
┆Issue Number: CON-11
