### ISSUE TITLE
MOCK WES-service via consonance

### ISSUE THREAD

**Issue by achave11** [BD2KGenomics/consonance#27]
Deactivate components of consonance that launch instances, and provision to AWS so that consonance can mock responses when is hit via server endpoint. 
- #26 implementation.
## Tasks
- [x] Explore and understand active threads in consonacne
 - This will help with future work implementation like delete functionality
 - Permanent fix to reaper bug 
- [x] Remove threads that provision to AWS and communicate with AWS
- [x] Create treads that update work via time delta.

**Comment by achave11** [comment]
Running update script in cron job. 
Refer to #32 to see script. Consonance running headless, no aws credentials.
